services:
  web:
    build: .
    command: >
      bash -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tournament
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/tournament_test
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tournament
    ports:
      - "5432:5432"

volumes:
  postgres_data: